# UNICAMENTE SE USARA SI SE NECESITAN EXTENSIONES DE PHP

FROM php:8.2-fpm

RUN docker-php-ext-install pdo pdo_mysql

# PRODUCCIÓN: UID estándar o del servidor (cambiar 33 por el UID de tu servidor)
RUN usermod -u 33 www-data && groupmod -g 33 www-data